language: scala
scala: 2.12.6
jdk: oraclejdk8
script:
- sbt ciBuild
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended

env:
  global:
  - secure: "owh1tDdkYJr29BHuzB5Snu1l6PKNlrjrsLe+dEyRF64FGGjI4zkljMf/MlstycgapBJ8Ii+1nmtlYYJloc4JgfSsjyos7sAABeAs+/7ex8bb3Ad0C0s4H2QbS/WzDvsnWMXQrR8lHa7Qkrn33VF6oPAhfWkZC5YuXXcUtkPPwhuf2jwTof7M6ZOMiFV1hZEJoH+MOI4H+2lt/vCTwnY+cqt9MekML6uwmgV48xJ592I5EoyL1d780hgVXZq7Qi7teQhlalGYj/KL/9YQPrrCzMUsnc6p7Kr4BOpYbLFX4KBgEGCuJ25T93S8M5oveunBIwNaFa7EKYxBMGD8QBXkOIR9OUSOFcy2Cx2SE0EklEpqU755C3cZwuqeV0pLNC3/MlOXe9q2+38BZCc6ttQVf3eq4UoFMhELMXVmtK4YS02m5JlpOvJu6oEEhobdQaL65VSmNF42bb4TUSpw70Wqoa+RHuqPZn6rVB1wNRZKl0zoylLrKb5YFYne9voqaw3yaa6G1e+yng/uwuN1pY3eMPDZjejwLr2bb2DQRwVg4mnS6rq809PFs8Qwd+QiNSlKLXK7drsW2vtMT7N3RmQBLNZJ2xQUvQcXxMLPg66e57pX3hA9L7Wj/HsXnNPpivL9ddN0L3BNKcg9zJJENIZV0Rkk8GbaRPc9HuIjIHn/TAU="
  - secure: "jx2hPJd6TvK8casS5PHaoz8aUUqDGGLeXDHVVihXBHowU4jZum8/YUT6UQAVaIvfutTHjXk4XwnEO0ZvwOQmywqoK/vLhRafWiIbIQ6MzchvgxeZ5Z+Z2ax55iUuothT5MnZ4ZGjyDeSAnldgZKAH+yGUN3+8N/K8c7Qqn0Cb1/xxRpz14f/cKQNaV3iXvDt092RbnP3X5epGJ3MB+NBlgzELbM8uYdciklZsaLjnoE3Suw7VN4PTiHJVApW70B4GUOjmbAAg9HUo7bh74GJAqRPD85ye3pnjoxIUJds6oonRzFZpseQjMlzyKrw2r5l+t+P+0T1MCefDtSDp5BRGvCm8WW/FRBSCozQOUPYlLlcPeorTfqvPjwS9SyZbk2xGa9uhUX4dUSpF1gWQrCkLkLacmh5zM4PlGpdludARLbY5lYE0b4yIckk6rXSwLoOh4jArIk0msCqBjSgwbOIF2mDK4E0lcQpFo9y4+53/8E0fLasq9JlhV++nQQt4vBttaO8x3+WPgJxDeI7Uln6GvGM4StVdk+6mtpgDYHaYpVIUZyN2c1N2kf4KdEwbk38tzJ52y4qIL7JtEQCIJNI0hbOvc7CvrLZkhdk0TuKlxmXJaXnCuxS8FQgt2hUqdFiotFe84jBWmoh3uHgGe0W/P95myEfZ3z/KbddPMdSOGs="
  - secure: "RIyGUN58G4aX4RKDX8R9qiC6QBhOzxfDhY66+9i8CeEVFS4CkSam2jNzteqh09IWaHqnmrCMTV3kobwnUEOK1eGOZk5ZuWA8VGEMHn7N1kfAVIT0MI4n8/DRF6dYcVZZODqMwdwyJBbhx4JcNRW18kBIvjSeszU7zgIZ58PI1tufnSd+34V0DIXnYHhDvM3zVwgUQrE6nvfzD7UyDv+BVJSYp4/tcHIN1loOvSlCXQzqtWSYkl67d+kKL9vIrDox2Dn7cbrdaEmtcJ+OlxC58udUSEs72njPrkUKVYu6ucvY61QOsl9J7Yi8KTCqhkTUcXKLjYd4UOqUqaqy7RPf8Wh461UmeF3wOFgziLIunca2kqjOwgOa8cqxS/IXyJjAQ2IuFB8VpOQQ+3rkjvgJ4+RBZRHwRTbhxbX4U2HqDKd0lb/z8osrzRafeKqqWEmdK0p5PpIkBggtonWRfVOlKmaVRALNhHK1DpXWEaPF50hQfJ/Lf/ph4FbDvYEoCqmfAjO1lxpnM9xxSN+WQGoEoFfuXHie2GgzxSrALQ/Vm0obqBdS9YkDk1vmI/b8OfDfH/xi2LYfKV+XCw7T8mrVilCCljcogbv8RrxYpE4YWENVDrtrx5xnofzOKoTK3DDuAa5wmrLm+agnaiq5BEqBvutKfb4Il0WlanwAOJgyMQ0="

stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push
jobs:
  include:
  - stage: VerifyPublish
    script: "./verifyPublish.sh"
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: "./runPublish.sh"
