language: scala

scala: 2.12.6

jdk: oraclejdk8

script:
- sbt ciBuild

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended

env:
  global:
  - secure: "ZhzAH05Iri4tqVezynpIB7oj3SpbuHDt/vwvBJMYSVdcu8PDxOF0/eDbmxUt/eBJNbd4I6uItTO9qa3NK89mUVUbq6FNzJmpMCliHCT6diHSME5JueZhQGGYnTv9I41TUM6Qy/Pwj4C0hnvolRQVyNTS10vUwlixj2qzWRgMZ2VjLLHtUDPLJ+j/y0B8OLFUYFB609mzJbDW1pyIpawTGtyFTmV9x2BsH3mrmuWZp17p0T9OmCIVUU/H4OBRNoTG+qS/b6mksWZD+VigT0CZ5fnOny2vXTU/OxrpXPv4h3Q0V2T316xioSHsvGxiGKUDVwpcjEMdhusXLoeVMXdh3O8UjKvWJGJ2OKaYE1lVX/FvOI98wcj4WiVazKfHo0h7HbVV113xedQSbdJwB7G/QndFZE1urauHIvhd5yJ7UN4FxdUjzFZYQq2Te/rWAutzkolo284m3tkdCYqbIhD6lIy0KlrfTR5xVoJIlYQuUuFNEovf4MTAkpBEpvbhUcUe1tNAjPGH1rmoNNa9ynsatRrhXZfrBjBSDxdHBHdzwXOXgLrgaaLclVApuAI4gec0GXD9Rl+jUJ1LtUiHFFs//o5XyayZgh/AFzm89cA+dxpS7D556EXcsp4VKRLRYhKxYPXeKghZlH0uYCTep8K7WETOj9WjdlR1qLXGkBNEJNM="
  - secure: "CNi7dC8rAljjZm9P8cgGgvRiHZaVB63tbkqNsLv2BZagMeSdEh3r4hr/p0ApZ6IeWpQuizWtyDKXOc+oPI27dhopvsVa9JOd/LYaAjH/JSA1fCBmmty1/fFdHqQ3clsixBlwNOhnXEv2sdaT63uugQYGummUNcdGrpfzZF+Fa68fkVajo+pcXxQPB2kA/BqVXIUhP1e7wvOqFO3oH/ub4GOTyaaJk7+nx6Su5l46FQTu1MKg+bQi+zNSL0f5FId76sBRPNn05aI7gsjwFMB/mUGxqfdD3VNI0rHeFuWqbXaAgmvUTYeoWO7wxMAg6shy+BsPktbygOf7wmFxyzfPvq7jH5lnXh7VDBRbVhAT8iwq+8BBH4h8N3klS3YfPo9+1R0JgJFdlO7yuKLvFBmKFLtPkRuIs16TxDWIBWtFyIsr0Xrj2TMoUsEHLFfNRq8WAFB8HJ3TrMUOcybw1r+i8GubD9SnOEAYoqHw/4167IyHZiBEQHXjWP2YB5KYAe8PM6XDLoDyrHczVYcsBLZlxp3rz9pyHizNLNEqvFebND+qUTVMWVHF0WaO68XE0nCJx/7ExnS1KKPqcS7wbSepz728sYRxtT0nkUCKXg+NpNHOCkCjt/e06JplRF/vtt43CqL709GtmaDi1N6YXrxelYj1scW9NnPp40uibWEFPes="
  - secure: "o1CNVkG2zryybgKIk5a7N1hGfrSoYV7vrLjsKwBiLdj6C117yIDvhod7E568+iz6t0FH4VbTWkyR5W2qK4FOjhxb6iVapuxeQBGgss5B5WL3cCb7EH6VeHDQ8SyQlrmCGQs4lK5cOYYiyi5v7frjj+UU11vvELjEfKOIkDTWZ7IgOokZ0r9V2bjzSmRTo6JQTXfa7t43w6zyVxGA2IEPC6kW277PdIZgk0JMe1fr6e4dKtySB10hii+eK355QfQrlY3KO5SibANP9S5sfUpQw1vVlMCbJ70HbPUdL3F1cgWqEz2EyKgtyyLbAuf0uVX1WuDK1N8eVSUi8xAcs4WxRCv9WoyplBNUk8zY0Xrccikc1WAW+iMVEEGbAgZLR+Sy1wMEeJI4WOMk+yshy18Pmz8+s0N2eTlBAcBZ8lZXDZMFzSv83XJQquvOmj7dI8rUSPZKyAiWmOJsZ3W9o/J/lUcbL/baBI67V2rzg4+HWllTMB+ysM5FRQtGsRzbsHOXSJiQV8RZ8IXRnBV5r2ovOHikyfY/pzW9lsBuQWiQm5MMRenPXZt+KX6ID1qnt+TyRthL3/VtALfgNZgnFvPZHoqGJapkNbJ1e0XT3JOG9MXSvoq/UrBcBYcde5/1wZWo69MAD4jVQfW+Dt5tn3GPHe64c/zeo5GfgsrOxFS8UFU="

stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push

jobs:
  include:
  - stage: VerifyPublish
    script: ./verifyPublish.sh
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: ./runPublish.sh
