language: scala
scala: 2.12.6
jdk: oraclejdk8
script:
- sbt ciBuild
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended
env:
  global:
  - secure: EHDLasSZWyVH8t/rL3OqG+U70YZOArnzZxJS10AHSl3YeY7BiKnOWI1cGzLuLFemJhzaZdgX/1D8DRTDA/6Y/O7FuVIUY6uaIG+n58Ik9M0Mts48N1VjhZcwKe//aah7bRLWTuAqZEua0sZGf8Cx2zwD1OO0R6W45Sd0u5Pjjfn/qOni43C90thTM/dvOWIeBQSzOwh/OirterNcShaxDtnojFf2Nm4EhkiVuTPdEdlJJUL2X8r8bOKCZrZMpyMvoe/JRpL4gQcfzsBlP7IoPLpt2+L287L7SgZ+ExNsEAWSyI83uNjZR+9DGFLzJCVumn0RJznHyvzFGNFYJD9JuHoyuFytK7wBzAVqRyPN2Wr0OYs4ix6M2pTN238gIB2JMMlwUfmx570vHqMTQNxtfPGvXVk939CDTEaoYKK553A5cMhD4KQKMmzENh1juFWeACWEW7DQhYyBvpm8/P3NkT1+AhTW6TooX1N5BwsNC1MbHGl/P718uGroutkTEoruKXBsmA2uj7ce8yKAYxidZntqaQqY/NAlXmJd4n/SdNVuHVWlM6LRwvC3GenT1KoejGR8ubMiDr1cQ6d64BDHlQGS2cUigCWKFaNGm3rZ5nDIpPSVqBVpaYZL7E+czabUvHvX/n7zs+5v3yvehMTzK8T8gAxszH3VVLsAhwnTas8=
  - secure: CRiDYbLNa0gycHg5Mh78V2+txfCpLHcOKP/rG27DMW2I/AMpN+YCXiQrTQmVmxRAP2g08x3Q1YxsnRNBZczEiiRSXw1BEDqDJ/iaLspshlWYqymX9cajenHOp+Eo/HF1SrWp34WdyFoC7uDwDUrwp/IyRnzZopaPHEmWZnEdDZGiT9l24Yy/eHEX0ueF5i95ey28q3h/uHVyxA9oYvnm9ZQzsyAw5JdiLjSkvtPMa4BRcNMTIA+ot9H5YzZt2IcOM+4ZHmUV0Mieml4ATpUBHbKr5ToZ4BMG5JojbkYSK8GYNpsM2Xxa8IX6n5RnkPuJ9J3LT9jnCPiElrJiS+/5E59lT5vyzv5wc/8P/xCtximoi+AsIT6q6DBWTpyIMDfFBKFmm9SHnjQFg1m2rV597TvxpPh4nfnT2yefOUPIJmKGgz5F2dBaldvsrQimVTN9FD8//oFcR4cGpiYUa1xR4tLBEjwFSbs5krZ5AcMuQhOim1yLL7ow44RgkLa6J8iQzUAYrRUPlXdspLqTjxyCy6uz5I3PuO4dLBHD1rGhMIpUmJfohcpjQbI2Xq5iF6NuORpjwIIoQDg+QiCSOlFFxu3bMc2OkiC322ydTHQZG8kvyPSvV8A1RU8DrlyXFX7L4Xg4iRRvec+dTXYFHKa5GykFjR3VgqR0W1KRsFhXsHs=
  - secure: QR1pU45b+d2U3yGjn7QDs/57z863btiujMeGgBBRt75xLqIYbxlvXULAAjamqWfXwS/72o37X7WyVX1i69vCMLcWpJPoj4IuphSNBlIMwMSyx9/GwLhvp8w10BRJGRdLmpfbu7jHD4kHGANyFL889Rak3wZWqU0bQzQrhR2HHZhMOl5bYHiDMLtWpIHMPnWfR5qf9I2l8RHI3ADOkeqT6rEQPRVEM0QsEf0itdsbMHP5hI7PkxsBSG6eABEwioXSsJzJQGx6/hneDvmj9k0ifNGu3Hq48XlQPUn07W6wxDjYDdDQIpEpTGVjZv4FOU5wV4lsDyVABL6bPlnBrdpF+q9/JT1Za46Z5FNYDSosWGvDUtFtrSvNnCunqeQnQvUPTgp8d82CnwdmziksA5umITZIrBHOJDPZTNLFXOSpx7PyDymHfaMAGVsTmuTkFYuKxPT63UjXWvL2Bfi0XzPyLN2pfHKtJ7p9nh6mexFccTFrJ/YioFvERnpFLHCOwgfLYPGm+BE1u6c4pwu8s9IZ3C6ujVOzBWneuQn+shqaJfSeJ0Q5buexgCENqP+ywaM0GZSvxBI/48VhwZ5iNJ5TD47rXx6a0aROxhMGUrjLbm3vgQIYwU5ykGyuhVKFHrYt/0bFVGwFzrWVhIJyoWaVyq/CooT8Oxun9pmbcvQe2NY=
    
stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push
jobs:
  include:
  - stage: VerifyPublish
    script: "./verifyPublish.sh"
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: "./runPublish.sh"
