language: scala
scala: 2.12.6
jdk: oraclejdk8
script:
- sbt ciBuild
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended
env:
  global:
  - secure: R+hoZ2h3wqSJjOVNE97cyv4bY9Xn9m8hSgyw9iXAnF8pIdQoEQuOppJOMtbkMLdZemKGYf0YY1ABZdt6m5kaTFBf4Vs6La3j6ogD+AZfVhWYsDOgejvEFR6szbiMbtA4u+ejqgC3VtHfYLwvaMYBJf2tsS54/FIPNBBWL59UJPri7IfFUfXP2GtRW8unerA7CagKicukzWBjAIqiKXW6o5N+OUHDlwgzPjZIk5S7xDeDRXNxRv3HnPk266s5YA/msGZzwnWiNy70jag5HQmaxDd8R/myXMDZbVanKwxQJtmubR5PBOYYDetteOTn3oN91ZHSjN0NF9mbpBJZDBAeKU8OhTJ1U8WOQ51tzclAaWzWygHQT+AWDbP2HikGHArCyt1SlVot4K0IaEGOMRK5TCA8ncGQDUWj1M2rzMUfiRRtR49j0AsnIiK1NOgH9mSrIvQbqLI0U6pST3pkBHeAP6mTUHYQu/mHGa46jkJd9DGhLu2n6QreBRm6IRlCXCgZogPYhFG8DUpyQEnry9rHN5WS4lokCtm8rqCDyR3D+NS0nkgRMHh4o4zAC4gTobXixySanKCiQhki+dEv4f2DRhg0ogoN2c3DCPSSULIopqiAnDB7j7bEvg9FAtooFziYqKl4JWMgzGBFg3HGqhKm1xI2PRdXCa6v7/Ps+iwZ1Yc=
  - secure: jGotpMfgunxQIy9iZz1qnEOA6Z6fahw3j4/+Db/vw+oXo9rCabp3rTvxf1mWgILFfRRqOxuYUs/G6I/N8QtZghxQ6ZRt+RfAUD4lWRKNDlCarakpdCHHGV8ANfdBvUfc+tm1JVNCGzs19Nrzn4FYHRc2AU9RRry0imabqxjW2BKoL6CD/AYewDNUD0TUQ1foj4hRzg1guYBPynLPJdBRhiZE0EPd44czOpnmDDiNAY5VRU5GsMIHuzo/F2FMG+Zq3t/342zUHsnCbe6q4vTZMV3zYrQe3EzAt+4kaZQkDHOhyCSZpwT5R0LFtR8NH5Pbi0JhsUIwcrp1fPCqFgHjpNE1Jh1sgqUPQzXBiPtuMN3uZufYyniyUO54BQJwuWqIGEhfXsV5MKOqD3RUKRYnSQYzBEJcV0Zo6xAyXEi+cGlMclvZmoDzOl2xjrv+sqgiCGL8MdYhgACxPGuTPOFOrMuisAtSpasClN6NUtd+h3pU9mPtWI2bViRb/kAw76K4sHJPYYPNHWJFusXZeK0UgScftfq+2aN7reeQpAtZTuT25aw+ckN5wExxZ07Y+/bNq2tLuq4jwlNuSJS+fim4AB5S7KMf/HGG6TIeMoPQMCyMrlpAOZcnfYmSgTaEcNfRX7KkYJfADKJvCpAyBzt27tosNeQzWw30JafPQ+MknJQ=
  - secure: ecEh5Qv+qbNiq0Wv7t3fMzn69TCymXEpZSEnTl7Q61PQgSuenrjQIG/NKSkROIeK1x3DljeDXTb3C+wGVb1znuuLU1dPUEsatWrMKvCj94mlX81H2qAwDp9hcj2c6H4MWOQ0V1IPP+GwI7nmx4i3h6fGwJ417NQlyQhyR+GwYxoG5bxye5HgguZFOvP4DyfDUuUR4kEty3riL1hn5DawEpKA5gNnDjC9JSrFTWrHjg9gJBKC6oYdhYmRYOwJc4d82UvJNV4iNtrDmHSFuDQnXUHdYmMGxllYQ46aqlxb7kyVo+VjAQEjN0KpQgs0U3Xq9Nkf5WHGfAQQhLpa44WHBsT35OvKPhSvYHB2e9EuLANjby4jsSln9loMwMfxvZ55TaVw03dl4B5laZkz1STIDXxMij6h6CZ0iLiaPJkaIkLWTbi8SBKNLgOs0B+Z24C1DYIWWEu/rEn9OfyYXk2o27d/ggDbrVadhHTjS+FZ4Oqo2WFtbk9K9Oo1zO8kzPcZmiEPlWVLmWf7BNb4BLxFe3/t9enV2z75Ocw3Ey593DUJGkWjzQBh9/vfZoybq6vAuDdWun35tTZb4zvu2SxbAIeC0ek508DKONLvGijKEL9YPa/dAFGwl/W9WORRuzpk92n7Jo2BUirkZBDXpBRohtrfcu9FGLEctm4T6NeHjis=

stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push
jobs:
  include:
  - stage: VerifyPublish
    script: "./verifyPublish.sh"
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: "./runPublish.sh"
