language: scala
scala: 2.12.6
jdk: oraclejdk8
script:
- sbt ciBuild
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended

env:
  global:


stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push
jobs:
  include:
  - stage: VerifyPublish
    script: "./verifyPublish.sh"
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: "./runPublish.sh"
