language: scala

scala: 2.12.6

jdk: oraclejdk8

script:
- sbt ciBuild

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

before_cache:
- rm -Rf $HOME/.ivy2/.sbt.ivy.lock ; rm -Rf $HOME/.ivy2/local ; rm -Rf $HOME/.m2/repository/de/wayofquality/blended

env:
  global:
  - secure: "ZhzAH05Iri4tqVezynpIB7oj3SpbuHDt/vwvBJMYSVdcu8PDxOF0/eDbmxUt/eBJNbd4I6uItTO9qa3NK89mUVUbq6FNzJmpMCliHCT6diHSME5JueZhQGGYnTv9I41TUM6Qy/Pwj4C0hnvolRQVyNTS10vUwlixj2qzWRgMZ2VjLLHtUDPLJ+j/y0B8OLFUYFB609mzJbDW1pyIpawTGtyFTmV9x2BsH3mrmuWZp17p0T9OmCIVUU/H4OBRNoTG+qS/b6mksWZD+VigT0CZ5fnOny2vXTU/OxrpXPv4h3Q0V2T316xioSHsvGxiGKUDVwpcjEMdhusXLoeVMXdh3O8UjKvWJGJ2OKaYE1lVX/FvOI98wcj4WiVazKfHo0h7HbVV113xedQSbdJwB7G/QndFZE1urauHIvhd5yJ7UN4FxdUjzFZYQq2Te/rWAutzkolo284m3tkdCYqbIhD6lIy0KlrfTR5xVoJIlYQuUuFNEovf4MTAkpBEpvbhUcUe1tNAjPGH1rmoNNa9ynsatRrhXZfrBjBSDxdHBHdzwXOXgLrgaaLclVApuAI4gec0GXD9Rl+jUJ1LtUiHFFs//o5XyayZgh/AFzm89cA+dxpS7D556EXcsp4VKRLRYhKxYPXeKghZlH0uYCTep8K7WETOj9WjdlR1qLXGkBNEJNM="
  - secure: "CNi7dC8rAljjZm9P8cgGgvRiHZaVB63tbkqNsLv2BZagMeSdEh3r4hr/p0ApZ6IeWpQuizWtyDKXOc+oPI27dhopvsVa9JOd/LYaAjH/JSA1fCBmmty1/fFdHqQ3clsixBlwNOhnXEv2sdaT63uugQYGummUNcdGrpfzZF+Fa68fkVajo+pcXxQPB2kA/BqVXIUhP1e7wvOqFO3oH/ub4GOTyaaJk7+nx6Su5l46FQTu1MKg+bQi+zNSL0f5FId76sBRPNn05aI7gsjwFMB/mUGxqfdD3VNI0rHeFuWqbXaAgmvUTYeoWO7wxMAg6shy+BsPktbygOf7wmFxyzfPvq7jH5lnXh7VDBRbVhAT8iwq+8BBH4h8N3klS3YfPo9+1R0JgJFdlO7yuKLvFBmKFLtPkRuIs16TxDWIBWtFyIsr0Xrj2TMoUsEHLFfNRq8WAFB8HJ3TrMUOcybw1r+i8GubD9SnOEAYoqHw/4167IyHZiBEQHXjWP2YB5KYAe8PM6XDLoDyrHczVYcsBLZlxp3rz9pyHizNLNEqvFebND+qUTVMWVHF0WaO68XE0nCJx/7ExnS1KKPqcS7wbSepz728sYRxtT0nkUCKXg+NpNHOCkCjt/e06JplRF/vtt43CqL709GtmaDi1N6YXrxelYj1scW9NnPp40uibWEFPes="
  - secure: "Xxkb2UmdWAiyZImEgaqUR7SCByeWMTtFBak7QmnLuwF0jFQqwHS4T6VySeo3Q2sUxJOQe62aNn3kxf3QffKaP1I/EYeVyqpfxrRam4IIjLayl4+P2FixOvdzcs6Ya8vwe2PuC+Lyi10S6Cdxqxx2vH2opc9qH9nAvLXO/FG9T8IEoL3KVI2nqc3A2DxBfp2Bu9pyikdrOevyfdYzPgGG2pOLMUhaEkK1ZkZk8CHBFXKcXQ4nzSlzg3VYv4b5PEFSsLQL4eyyANCj0bwxyH7otmzwyecxFu00zNK2wkhB6JDPi0htMvb8hegYtCBLDfltVqC/UNZz3xcmcVs/ViIC+kIVA4R6E0by7TCCg9gGjZ91NfY3G801TXTPxjvLJ5wY6HkHXCHCF0K+z+aJvPj1WK5BJdTNizjOTNXLe4HUfeOJz+jVJH5ny2zo39jkLbyOD5JGqcNuEMc/i/wVvnvpDg3AsURjkOTjE9fKNcbDoprEJS76eAAhWkY8Th58rS33JCu4EoXQzoJxwHsXMANVIhN5Lzv+N4x+7Z+9ohmdvINaW21RAXF5TmQD4G91lxS9DaRJ0ctfxBh5uPDrKcF28l/O1hEeZagBTAZgTuqwWq5pXuQhuJhf2FnYFFhI3243dW48wIOzC9WQn+w1BRTocn2r6Do2o8DoFoj+kxopvUU="

stages:
- name: VerifyPublish
  if: branch = publish AND type = push
- Test
- name: Deploy
  if: branch = publish AND type = push

jobs:
  include:
  - stage: VerifyPublish
    script: ./verifyPublish.sh
  - stage: Test
    script: sbt ciBuild
  - stage: Deploy
    script: ./runPublish.sh
